# Generated by Django 5.2.11 on 2026-03-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
