# Generated by Django 6.0.3 on 2026-03-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
