# Generated by Django 6.0.3 on 2026-03-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_file_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
